<?php

    // Main
    define("_MAIN_TITLE", "Adrià Alberich - ");
    define("_MAIN_DISCLAIMER", "All the content and code of this site has been generated by me. I don't use any third party library or framework. Third party images and logos have reuse and modification rights.");
    define("_MAIN_SOCIAL", "Follow me on");
    define("_MAIN_PAGE_LOADING_TIME", "Site has loaded in");
    define("_MAIN_LEGAL", "Legal notice");
    define("_MAIN_COOKIE", "While surfing this site, you accept that it uses cookies as stated in our");
    define("_MAIN_COOKIE_POLICY", "Privacy policy");
    define("_MAIN_EMAIL", "me@adrialberich.com");
    define("_MAIN_DIALOG_ACCEPT", "OK");
    define("_MAIN_DIALOG_CANCEL", "Cancel");

    // About me
    define("_ABOUT_NAME", "About me");
    define("_ABOUT_TITLE", "About me");
    define("_ABOUT_HEADER_TITLE", "Adrià Alberich<br/>.NET Developer");
    define("_ABOUT_WHOIAM_TITLE", "Who I am?");
    define("_ABOUT_WHOIAM_P1", "I'm Adrià Alberich, a professional .NET developer for more than 6 years. My passion for computers and technology began about 2006, at this time I was 14, was then when I had my first computer with broadband Internet connection.");
    define("_ABOUT_WHOIAM_P2", "It didn't take long before I started learning how to code websites and simple applications by myself, at this time in HTML and Visual Basic 6 respectively. Then it became one of my main hobbies, mostly focusing on videogame modding tools.");
    define("_ABOUT_WHOIAM_P3", "Around 2011 I decided to start leading my studies to professional programming, and I began alternating between studies and work. Initially I focused on web applications, but then I migrated to Microsoft backend technologies and currently it's my specialty.");
    define("_ABOUT_HOWIWORK_TITLE", "How do I work?");
    define("_ABOUT_HOWIWORK_P1", "Inside Microsoft technologies, I'm specializen on .NET and C#, as I said previously, mainly on backend applications and APIs. However I'm also fluent with frontend technologies like HTML, CSS, JS, Bootstrap, and recently Angular.");
    define("_ABOUT_HOWIWORK_P2", "I also worked with Microsoft Dynamics 365, and recenlty I started some digging on Microsoft Power Platform and Azure.");
    define("_ABOUT_HOWIWORK_P3", "On the database side, I have good knowledge of Transact-SQL, I worked mostly with SQL Server and MySQL, I also have a bit knowledge of Oracle databases. Currently I am learning MongoDB as a NoSQL alternative.");
    define("_ABOUT_WANNAHIRE_TITLE", "Want to hire me?");
    define("_ABOUT_WANNAHIRE_P1", "If you think I could be usefull for your project, please, do not hesitate to contact me. I like new challenges!");

    // Portfolio
    define("_PORTFOLIO_NAME", "Portfolio");
    define("_PORTFOLIO_TITLE", "Portfolio");
    define("_PORTFOLIO_HEADER_TITLE", "Portfolio");
    define("_PORTFOLIO_HEADER_DESCRIPTION_INTRO", "Here you can find some side projects that I worked in my freetime.");
    define("_PORTFOLIO_CARD_PERSONALSITE_TITLE", "adrialberich.com");
    define("_PORTFOLIO_CARD_PERSONALSITE_DESCRIPTION", "Personal website and portfolio. From the ground up without external resources.");
    define("_PORTFOLIO_CARD_SADEGELSTOCK_TITLE", "Sadegel Stock");
    define("_PORTFOLIO_CARD_SADEGELSTOCK_DESCRIPTION", "Automated stock control system for italian ice cream parlors.");
    define("_PORTFOLIO_CARD_REDRP_TITLE", "RedRP");
    define("_PORTFOLIO_CARD_REDRP_DESCRIPTION", "Roleplay gamemode for the RAGE MP platform.");
    define("_PORTFOLIO_CARD_MYCHEF_TITLE", "My Chef");
    define("_PORTFOLIO_CARD_MYCHEF_DESCRIPTION", "Web appliacation for hiring professional chefs.");
    define("_PORTFOLIO_CARD_GAMEINSTANCE_TITLE", "Game Instance");
    define("_PORTFOLIO_CARD_GAMEINSTANCE_DESCRIPTION", "Cloud-based game server mangement system.");
    define("_PORTFOLIO_CARD_BUTTON_LEARNMORE", "Learn more");
    define("_PORTFOLIO_SECTION_PERSONALSITE_TITLE", "adrialberich.com");
    define("_PORTFOLIO_SECTION_PERSONALSITE_DESCRIPTION", "My personal website made from the ground up with HTML5, CSS3 and JS. As a personal challenge, I decided not to use any tool or external resource.");
    define("_PORTFOLIO_SECTION_SADEGELSTOCK_TITLE", "Sadegel Stock");
    define("_PORTFOLIO_SECTION_SADEGELSTOCK_DESCRIPTION", "Stock control system for italian ice cream parlors. It was a quite complex project done while I was working as a freelance for an important ice cream franchise. The system controls the sold products and calculates the amounts of ingredients that are being used for the production. The system works with an automated bot and a desktop application that allows to manage it, and generates alerts when there is an excessive use of ingredients or there is a waste of products.");
    define("_PORTFOLIO_SECTION_REDRP_TITLE", "RedRP");
    define("_PORTFOLIO_SECTION_REDRP_DESCRIPTION", "Roleplay gamemode for the RAGE MP platform and Red Dead Redemption 2 game. It was done with .NET Core and C#, it features a character creation system, progress management, personal inventory, chat and admin system.");
    define("_PORTFOLIO_SECTION_MYCHEF_TITLE", "MyChef");
    define("_PORTFOLIO_SECTION_MYCHEF_DESCRIPTION", "This was the final programming school project. It is a web application made with PHP (Laravel) that works as a social network. The chefs have their profile pages and the rest of the users can search for them and hire them for private events and parties.");
    define("_PORTFOLIO_SECTION_GAMEINSTANCE_TITLE", "Game Instance");
    define("_PORTFOLIO_SECTION_GAMEINSTANCE_DESCRIPTION", "Game Instance is a recent project. The idea is to make a game server management system that can be easily deployed in the cloud. This is meant to be used by people with no technical knowledge. It uses the most recent technologies, like .NET 5 and ngx-admin (Angular 9+). Source code not available.");

    // Contact
    define("_CONTACT_NAME", "Contact");
    define("_CONTACT_TITLE", "Contact");
    define("_CONTACT_FORM_HEADER_TEXT_1", "Anything you want to ask, you can write to me at:");
    define("_CONTACT_FORM_HEADER_TEXT_2", "Or, if you prefer, you can fill the following form and you'll receive an answer as soon as possible.");
    define("_CONTACT_FORM_HEADER_TITLE", "Contact");
    define("_CONTACT_FORM_PERSONAL_TITLE", "Your data");
    define("_CONTACT_FORM_NAME", "Name: ");
    define("_CONTACT_FORM_EMAIL", "E-Mail: ");
    define("_CONTACT_FORM_PHONE", "Phone: ");
    define("_CONTACT_FORM_MESSAGE_TITLE", "Your message");
    define("_CONTACT_FORM_SUBJECT", "Subject: ");
    define("_CONTACT_FORM_MESSAGE", "Message: ");
    define("_CONTACT_FORM_SEND", "We're almost done...");
    define("_CONTACT_FORM_SEND_PRIVACY_1", "I accept that all my personal data will be processed in accordance with the");
    define("_CONTACT_FORM_SEND_PRIVACY_2", "Privacy Policy");
    define("_CONTACT_FORM_SEND_PRIVACY_3", "of this site, and also in accordance to the GDPR regulations.");
    define("_CONTACT_FORM_SEND_BUTTON", "Send");
    define("_CONTACT_FORM_SUCCESS", "Form sent successfully. You'll receive an answer as soon as possible.");
    define("_CONTACT_FORM_ERROR", "Can't send the form, please make sure that you have checked the 'Im not a robot' checkbox.");

    // Legal
    define("_LEGAL_TITLE", "Legal notice");
    define("_LEGAL_BODY", "The site adapts to the different regulations and laws of Spain and the UE like GDPR. Executing the needed actions to ensure the privacy of its users. ADRIALBERICH is currently hosted on France with the supervision of OVH Inc.");
    define("_LEGAL_OWNER_TITLE", "Accountable");
    define("_LEGAL_OWNER_BODY", "The domain adrialberich.com is owned by Adrià Alberich with Spanish ID 47997458T (me@adrialberich.com)");
    define("_LEGAL_WARRANTY", "Warranty");
    define("_LEGAL_WARRANTY_BODY", "The accountable warrants that the personal data of the users is processed in accordance with the UE General Data Protection Regultation (GDPR, 95/46/CE).");
    define("_LEGAL_COOKIES", "Cookies policy");
    define("_LEGAL_COOKIES_BODY", "ADRIALBERICH uses Cookies to store thing like the user's language preference, session data and acceptance of the Cookies policy advice. Cookies are memory spaces that contain data on the user's browser. The cookie storage can be disabled in the browser options at any time.");
    define("_LEGAL_CONTACT_FORM", "Contact form");
    define("_LEGAL_CONTACT_FORM_BODY", "As stated on WARRANTY section, all data gathered from the contact form will be sent to the E-Mail address me@adrialberich.com and used only for contact purposes.");
    define("_LEGAL_THIRD_PARTY", "Third party services");
    define("_LEGAL_THIRD_PARTY_BODY", "ADRIALBERICH currently does not uses any kind of third party service.");
    define("_LEGAL_USER_RIGHTS", "User rights");
    define("_LEGAL_USER_RIGHTS_BODY", "In accordance to the compliance of the laws stated on the WARRANTY section, the user has the rights of Access, Rectification, Opposition and Cancellation of all his personal data stored at ADRIALBERICH. It's mandatory to address an E-Mail to me@adrialberich.com in order to make use of these rights.");

?>